### Hosszú táblázatforma létrehozása
Flyball2024p2.jpynb

- Bemenete: flyballdf.csv
- Kimenete: szines2.csv
- Feladata: hosszú formátúvá alakítja az adattáblát, úgy, hogy a kutyák és futás/váltás adataik egymás alatt helyezkednek el.
- Külön figyelve arra, hogy mindegyik kutyának megmaradjanak a sorban a váltójára és a versenyre jellemző közös adatoszlopok.
- Ebben az adatbázisban van még két kód az elején, feladatuk:
- a W/L/T oszlop hiányzó értékek számolása
- kék/piros pálya oszlop szín kiosztása

In [3]:
import pandas as pd
#adatbázis betöltése
flyball2 = pd.read_csv('./../data/flyballdf.csv', index_col=[0])

In [4]:
flyball2.isna().sum()

Division         0
when             0
who              0
with who         0
total time       0
W/L/T          107
Hurdles         41
name            30
start            0
1.dog            0
name.1          75
chng           276
2.dog           54
name.2         185
chng.1         366
3.dog          168
name.3         248
chng.2         438
4.dog          255
place            0
date             0
competition      0
dtype: int64

In [5]:
#A W/L/T oszlop  107 hiányzó értékének számítása: NaN értékeknek a 'NON' stringet adjuk
flyball2['W/L/T'].fillna('NON', inplace=True)

In [6]:
#A NON értékek feltöltése egy elemző kóddal történik: eldönti a Total time idő alapján, hogy ki nyert 
for i in range(len(flyball2)):
    if flyball2.iloc[i,5] == 'NON':                         #vizsgálja, hogy a NON sorokban
        if flyball2.iloc[i,1] == flyball2.iloc[i+1,1]:     #ha megegyezik a WHEN dátuma
            if flyball2.iloc[i,4] > flyball2.iloc[i+1,4]:    #akkor a TOTAL TIME hol nagyobb, hol kisebb
                flyball2.iloc[i,5] = 'L'
            if flyball2.iloc[i,4] < flyball2.iloc[i+1,4]:
                flyball2.iloc[i,5] = 'W'
                
            if flyball2.iloc[i,4] > flyball2.iloc[i+1,4]:    #és eszerint átírja a NON-t W/L-re
                flyball2.iloc[i+1,5] = 'W'
            if flyball2.iloc[i,4] < flyball2.iloc[i+1,4]:
                flyball2.iloc[i+1,5] = 'L'
            
            if flyball2.iloc[i,4] == flyball2.iloc[i+1,4]:
                flyball2.iloc[i,5] = 'T'
                flyball2.iloc[i+1,5] = 'T'

In [7]:
len(flyball2[flyball2['W/L/T'] == 'NON'])
#a feltöltés után 25 sor marad, aminek nincs NON időpárja, de valószínűleg többségük kiesik a tisztítás során

25

In [8]:
#a place, date és competition oszlopokat az elejére kell mozgatni, hogy közös adatknék a váltó mindegyik kutyájánál lássuk
firstplace = flyball2.pop('place')
flyball2.insert(2 ,'place', firstplace)

firstdate = flyball2.pop('date')
flyball2.insert(2 ,'date', firstdate)

firstcompetition = flyball2.pop('competition')
flyball2.insert(2 ,'competition', firstcompetition)

flyball2.head(150)

,Division,when,competition,date,place,who,with who,total time,W/L/T,Hurdles,...,1.dog,name.1,chng,2.dog,name.2,chng.1,3.dog,name.3,chng.2,4.dog
0,13.0,1900-01-01 12:26:30,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,Real Ballance Flyball Team,WildRunners Zephyr,21.18,L,15.0,...,4.21,Rubble,0.64,4.89,Zuma,0.36,4.3,Marshall,0.3,6.14
1,13.0,1900-01-01 12:26:30,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,WildRunners Zephyr,Real Ballance Flyball Team,20.49,W,25.0,...,4.58,Them,OK,5.2,Negro,0.51,4.89,Speedy,0.4,4.93
2,13.0,1900-01-01 12:27:58,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,Real Ballance Flyball Team,WildRunners Zephyr,20.81,W,15.0,...,4.24,Rubble,0.18,5.03,Zuma,0.18,4.51,Marshall,0.24,6.42
3,13.0,1900-01-01 12:27:58,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,WildRunners Zephyr,Real Ballance Flyball Team,20.85,L,25.0,...,4.42,Them,0.37,5.19,Negro,0.2,5.27,Speedy,error,5.24
4,13.0,1900-01-01 12:29:11,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,Real Ballance Flyball Team,WildRunners Zephyr,20.66,W,15.0,...,4.24,Rubble,0.33,5.13,Zuma,Ok,4.67,Marshall,0.12,6.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,13.0,1900-01-01 15:14:55,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,BayernXpress I,JokerZ Lou,20.42,L,25.0,...,5.08,Sugar,0.32,4.05,Pepper,0.27,5.29,Berta,NaN,5.29
146,13.0,1900-01-01 15:16:13,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,JokerZ Lou,BayernXpress I,20.62,W,20.0,...,4.47,Pelly,0.26,5.79,Sura,ok,5.31,Árnyék,0.32,4.39
147,13.0,1900-01-01 15:16:13,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,BayernXpress I,JokerZ Lou,20.58,L,25.0,...,5.26,Berta,0.18,5.28,NaN,0.3,5.3,Sugar,OK,4.22
148,13.0,1900-01-01 15:17:45,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,JokerZ Lou,BayernXpress I,21.29,W,20.0,...,4.6,Pelly,OK,5.72,Sura,0.44,5.23,Árnyék,0.84,4.4
149,13.0,1900-01-01 15:17:45,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,BayernXpress I,JokerZ Lou,19.94,L,25.0,...,5.02,Berta,error,5.39,Pepper,-0.36,5.61,Sugar,Ok,4.19

In [9]:
flyball2.reset_index(inplace = True, drop = True) #újraindexelve
flyball2.shape

(8569, 22)

In [10]:
#ide jöhetnek a kék-piros kategória oszlop értékeinek számítása:

flyball2['colour'] = 0
for i in range(len(flyball2)-1):
    
    if flyball2.iloc[i, 1] == flyball2.iloc[i+1, 1]:
        
        flyball2.iloc[i, 22] = 'Blue'
        
        flyball2.iloc[i+1, 22] = 'Red'


len(flyball2[flyball2['colour'] == 0])/len(flyball2) #1,2% nincs kategorizálva, ellenőrizzük tisztitás után

0.012020072353833585

In [11]:
#mozgassuk a colour oszlopot is az elejére, mert ott vannak azok az információk, amiket minden kutyához 
#rendelni szeretnék

firstcolour = flyball2.pop('colour')
flyball2.insert(2 ,'colour', firstcolour)

In [12]:
flyball2.iloc[0:5, 11:23]

,name,start,1.dog,name.1,chng,2.dog,name.2,chng.1,3.dog,name.3,chng.2,4.dog
0,Chase,0.330,4.21,Rubble,0.64,4.89,Zuma,0.36,4.3,Marshall,0.3,6.14
1,Brix,-0.030,4.58,Them,OK,5.2,Negro,0.51,4.89,Speedy,0.4,4.93
2,Chase,0.008,4.24,Rubble,0.18,5.03,Zuma,0.18,4.51,Marshall,0.24,6.42
3,Brix,0.150,4.42,Them,0.37,5.19,Negro,0.2,5.27,Speedy,error,5.24
4,Chase,0.090,4.24,Rubble,0.33,5.13,Zuma,Ok,4.67,Marshall,0.12,6.09

In [13]:
#4 új oszlop beszúrása
flyball2.insert(loc=11, column='rank', value='1')
flyball2.insert(loc=15, column='rank2', value='2')
flyball2.insert(loc=19, column='rank3', value='3')
flyball2.insert(loc=23, column='rank4', value='4')

In [14]:
flyball2.shape

(8569, 27)

In [15]:
flyball2.iloc[0:5, 0:11]

,Division,when,colour,competition,date,place,who,with who,total time,W/L/T,Hurdles
0,13.0,1900-01-01 12:26:30,Blue,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,Real Ballance Flyball Team,WildRunners Zephyr,21.18,L,15.0
1,13.0,1900-01-01 12:26:30,Red,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,WildRunners Zephyr,Real Ballance Flyball Team,20.49,W,25.0
2,13.0,1900-01-01 12:27:58,Blue,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,Real Ballance Flyball Team,WildRunners Zephyr,20.81,W,15.0
3,13.0,1900-01-01 12:27:58,Red,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,WildRunners Zephyr,Real Ballance Flyball Team,20.85,L,25.0
4,13.0,1900-01-01 12:29:11,Blue,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,Real Ballance Flyball Team,WildRunners Zephyr,20.66,W,15.0

In [16]:
#a színes adatbázisok kijelölése
feherdf = flyball2.iloc[0:,0:11]
pirosdf = flyball2.iloc[0:,11:15]
kekdf = flyball2.iloc[0:,15:19]
sargadf = flyball2.iloc[0:,19:23]
zolddf = flyball2.iloc[0:,23:27]

In [17]:
#a színes adatbázisok újrafűzése, oszlopnevek egységesítése
pirosdf.columns = ['rank', 'name', 'relay', 'time']
kekdf.columns = ['rank', 'name', 'relay', 'time']
sargadf.columns = ['rank', 'name', 'relay', 'time']
zolddf.columns = ['rank', 'name', 'relay', 'time']

feherpirosdf = pd.concat([feherdf, pirosdf], axis=1)
feherkekdf = pd.concat([feherdf, kekdf], axis=1)
fehersargadf = pd.concat([feherdf, sargadf], axis=1)
feherzolddf = pd.concat([feherdf, zolddf], axis=1)

szines2 = pd.concat([feherpirosdf, feherkekdf, fehersargadf, feherzolddf], axis=0)
szines2.reset_index(inplace = True, drop = True) #eldobja a régit

In [18]:
szines2.head()

,Division,when,colour,competition,date,place,who,with who,total time,W/L/T,Hurdles,rank,name,relay,time
0,13.0,1900-01-01 12:26:30,Blue,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,Real Ballance Flyball Team,WildRunners Zephyr,21.18,L,15.0,1,Chase,0.33,4.21
1,13.0,1900-01-01 12:26:30,Red,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,WildRunners Zephyr,Real Ballance Flyball Team,20.49,W,25.0,1,Brix,-0.03,4.58
2,13.0,1900-01-01 12:27:58,Blue,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,Real Ballance Flyball Team,WildRunners Zephyr,20.81,W,15.0,1,Chase,0.008,4.24
3,13.0,1900-01-01 12:27:58,Red,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,WildRunners Zephyr,Real Ballance Flyball Team,20.85,L,25.0,1,Brix,0.15,4.42
4,13.0,1900-01-01 12:29:11,Blue,FLYBALL_EFC,2023-07-29,Tápiószentmárton Ring1,Real Ballance Flyball Team,WildRunners Zephyr,20.66,W,15.0,1,Chase,0.09,4.24